name: tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

permissions:
  contents: read
  # Optional: allow read access to pull request. Use with `only-new-issues` option.
  pull-requests: read

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - uses: golangci/golangci-lint-action@v6
        with:
          version: latest
          only-new-issues: true

      - name: Install goveralls
        run: go install github.com/mattn/goveralls@latest

      - name: Build
        run: go build -v ./...

      - name: Run tests
        run: go test -race -covermode=atomic -coverprofile=covprofile -v ./...

      - name: Update coverage
        env:
          COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: goveralls -coverprofile=covprofile -service=github
